sudo: false
language: node_js
node_js: '10'
install:
  - npm ci
cache:
  directories:
    - '$HOME/.npm'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # needed by nodegit (repo-cooker)
      - libstdc++-4.9-dev
git:
  depth: 9999
notifications:
  email: false
script:
  - |
    if [[ $SKIP_TESTS != 'true' ]]; then
      npm prune
      npm run deps:check
      npm run typecheck
      npm run lint
      npm test
    fi
after_success:
  - |
    if [[ $TRAVIS_SECURE_ENV_VARS == 'true' ]]; then
      git remote set-url origin https://fmal:${GH_TOKEN}@github.com/fmal/monorepo;
      git config --global user.email "travis@travis-ci.com";
    fi
    if [[ $TRAVIS_BRANCH == 'master' || $TRAVIS_PULL_REQUEST == 'true' ]]; then
      npx codecov -t $(CODECOV_TOKEN)
    fi
    if [[ $TRAVIS_BRANCH == 'master' || $TRAVIS_BRANCH == 'next' ]] && [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
      printf "//registry.npmjs.org/:_authToken=$NPM_TOKEN\n" >> ~/.npmrc
      npm install --no-save nodegit@0.24.3
      npm run release -- --no-parallel --print-release
    fi
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
